### ISSUE TITLE
Not an issue - Just saying thanks

### ISSUE THREAD

**Issue by MikeTheSnowman** [christiansiegel/knitter#1]
Hello christiansiegle,

Since github doesn't support private messages, this is really my only way of sending this "thank you" message.

Just wanted to say thanks for making this processing script available.  I used your script to help me make a birthday present for my girlfriend.  I'm not sure if you ever got around to actually making the knitting pattern in real life, but I did and it worked out beautifully.  I posted the end result to Imgur citing your script as what did the heavy lifting, making it all possible. 
[http://imgur.com/gallery/atlTw](url) 

Thanks again!
-wtfacoconut

**Comment by christiansiegel** [comment]
Looks great! Nice to see someone actually beeing productive! :D 
Haven't had the chance to try it out myself yet.

(Unfortunately, your link doesn't work. If someone reads this, here you go: http://imgur.com/gallery/pN5T9)

I also mentioned your work in the readme ;-)

-Christian
