### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by tommallama** [christiansiegel/knitter#2]
When clicking the Strings bar towards the end (about 9/10 to the end of the bar) I get a NullPointerException before the output finishes. 

This is without adjusting any other default settings.

Trying different images the exception would occur when pin 199 was followed by pin 0, but once it occurred when 50 was followed by 0, but the exception may be completely unrelated to the pins.

Hope that helps, awesome bit of code by the way!
-tommallama

**Comment by christiansiegel** [comment]
Thanks for testing and reporting! It was caused by not finding a valid next pin (all combinations used). The function determining the next pin always returned 0 in that case. Changed the return value to -1 which then stops the generation. See 1eacf58e8aecdbda78c0c121594c6523f1155ad6 for details.

**Comment by tommallama** [comment]
No problem at all. It looks like that fixed the issue.
Again, great work!
-tommallama
