### ISSUE TITLE
color version?

### ISSUE THREAD

**Issue by kitor7** [christiansiegel/knitter#4]
You code is so cool! I like it very much. Thanks.
I was wondering if it's possible to make a RGB or CMYK version of this algorithm using 3 or 4 threads instead of one. It would be amazing if this is possible. Have you thought about it?

This link https://github.com/MaloDrougard/knit have change to color ,random nails,and so on.
But I cann't use it with OF. Maybe you can change it to processing. 
Thank you.

**Comment by christiansiegel** [comment]
Hi @kitor7, thanks for the feedback!

IMO a CMY version should be possible with some modifications:
- keeping track of 3 threads + output instruction for all of them
- remove grayscale filter of input image
- modify scoring and reduction functions to take account of colors
- ...

Malo Drougard's [report](https://github.com/MaloDrougard/knit/blob/master/Doc/knit-final-report.pdf) also contains some documentation on that color implementation in chapter 4.3.

However, I can't promise that I will be able to look into that in the near future. I will keep this issue open as feature request -> pull requests are welcome :wink:

**Comment by christiansiegel** [comment]
Ok, I couldn't let it go :laughing: 
You'll find a first hacky draft of a CMY version on the branch [feat/color](https://github.com/christiansiegel/knitter/tree/feat/color)
