### ISSUE TITLE
What if square image ?

### ISSUE THREAD

**Issue by mrnann** [christiansiegel/knitter#5]
Hi christiansiegel,

Im also wondering can it make into square instead of circle ?

**Comment by christiansiegel** [comment]
Hi @alfred11111,

Yes, that should be no problem. But it needs some changes to add this feature.

Instead of returning pins in a circular shape a square shape should be returned here: https://github.com/christiansiegel/knitter/blob/master/knitter.pde#L145.

I'll might have a look into that in the following days.

**Comment by mrnann** [comment]
I see. I made a real artwork by using your code. Its round shape with a human face.

I wish I can do it with square shape too. Please let me know if you can make it in the following days.

**Comment by mrnann** [comment]
Also for your colored code, I tried to apply it in processing too.
But the image generated is not as detailed as your grey scale code.
Some black and grey area is missing.
And is it possible to also have number sequence for each colour line just like your original  grey scale coding ? Then we can really make it into a real artpiece follow the sequence.

**Comment by christiansiegel** [comment]
I made a draft version with the support for a square output: https://github.com/christiansiegel/knitter/tree/feat/square

You can switch the mode in line 12 of the sketch. I might add a toggle button for that. But let me know if it works for now.

Nice to see someone using this project. Feel free to send me pictures of your results. I'm also happy to reference them :wink: 

Regarding the color version: Please follow issue #7 for the instruction output.

**Comment by mrnann** [comment]
Wor. The square works. Thats so cool.
But which point should count as 0 ?
just like the circle one, the 0 start from 6 o'clock. Then 1,2,3,4,5......etc.
But how about the square ?

**Comment by christiansiegel** [comment]
![numbering](https://user-images.githubusercontent.com/13996624/84590573-1f9ce900-ae38-11ea-9d38-754aff6fdc6a.png)
